function aisresponse(b,a){ais_client.aisresponse(b);ais_client.log("aisresponse: Response Data"+(1==a?" (cache) ":""),!0);ais_client.log(b)}
(function(){function b(){this.callbacks={bounce:this._nullhandler,echo_response:this._nullhandler,chooser:this._nullhandler,init:this._nullhandler,identity:this._nullhandler,logout_result:this._nullhandler,becomes_authenticated:this._nullhandler,becomes_unauthenticated:this._nullhandler,authz_query:this._nullhandler,resources:this._nullhandler,device:this._nullhandler,vcs:this._nullhandler,vcs_list:this._nullhandler,authz_query_list:this._nullhandler};this.baseurl="idp.securetve.com/rest/1.0/";this.responsefield=
"aisresponse";this.authstate=!1;this.aisuid=this.platform_id="";this.use_logging=!1;this.log_target="";this.use_cache=!0;this.response_cache={};this.cache_time={init:3E4,chooser:3E4,authz_query:3E4,identity:3E4,bounce:2E3,echo_response:3E4,vcs:2E3,vcs_list:5E3,resources:3E4,authz_query_list:3E4};this.script_insert_type="";this.log_toggle=0;this.supportsLocalStorage=void 0;this.ls_prepend="AIS_client___";this.language_override="";this.protocol="http:"==window.location.protocol||"https:"==window.location.protocol?
window.location.protocol+"//":"http://";this.log_object={};this.log_object_keys=[];this.log_object_size=20}b.prototype.assignhandler=function(a,c){this._isFunction(c)?this.callbacks[a]=c:this.log("unable to assign handler to callback type ("+a+") because it is not callable",!0)};b.prototype.setPlatformId=function(a){this.platform_id!=a&&this._reset_cache(!0);this.platform_id=a;this.log("setPlatformId ("+this.platform_id+")",!0)};b.prototype.setLanguageOverride=function(a){this.language_override=a;
this.log("setLanguageOverride ("+this.language_override+")",!0)};b.prototype.setProtocol=function(a){this.protocol=a;this.log("setProtocol ("+this.protocol+")",!0)};b.prototype.setResponsefield=function(a){this.responsefield=a;this.log("setResponsefield ("+this.responsefield+")",!0)};b.prototype.aisresponse=function(a){void 0!==a.authenticated&&this.authstate!==this._mkboolean(a.authenticated)&&(this.authstate=this._mkboolean(a.authenticated),this._reset_cache(),this.authstate?(this.log("Authenticated",
!0),this._dispatch("becomes_authenticated",a)):(this.log("Not Authenticated",!0),this._dispatch("becomes_unauthenticated",a)));void 0!==a.authorization&&(this._mkboolean(a.authorization)?this.log("Authorized: "+a.resource,!0):this.log("Not Authorized: "+a.resource,!0));void 0!==a.aisuid?(this.aisuid=a.aisuid,this.log("Init: AISUID - "+this.aisuid,!0)):void 0!==a.identity&&(this.aisuid=a.identity.aisuid,this.log("Identity: AISUID - "+this.aisuid,!0));this._set_cache(a);if("authz_query_list"==a._type||
"vcs_list"==a._type)for(i=0;i<a.documents.length;i++)this._set_cache(a.documents[i]);"logout_result"==a._type&&(this.log("aisresponse: clearing cache",!0),this._reset_cache(!0));this._dispatch(a._type,a)};b.prototype.bounce=function(a){this.log("bounce ",!0);1!=a&&0!=this._use_cache("bounce")||this._call_ais("bounce")};b.prototype.echo=function(a,c){this.log("echo ",!0);1!=c&&0!=this._use_cache("echo_response",a)||this._call_ais("echo",a)};b.prototype.init=function(a){this.log("init: ("+(1==this.authstate?
"init":"chooser")+")",!0);1!=a&&0!=this._use_cache(1==this.authstate?"init":"chooser")||this._call_ais("init")};b.prototype.chooser=function(a){this.log("chooser ",!0);1!=a&&0!=this._use_cache("chooser")||this._call_ais("chooser")};b.prototype.init_increaseScope=function(a){this.log("init_increaseScope DEPRECATED, using chooser",!0);1!=a&&0!=this._use_cache("chooser")||this._call_ais("chooser")};b.prototype.identity=function(a){this.log("identity ",!0);1!=a&&0!=this._use_cache("identity")||this._call_ais("identity")};
b.prototype.logout=function(){this.log("logout ",!0);this._reset_cache();this._call_ais("logout")};b.prototype.resourceAccess=function(a,c){this.log("resourceAccess: "+a,!0);1!=c&&0!=this._use_cache("authz_query",a)||this._call_ais("resourceAccess",a)};b.prototype.resourceAccessList=function(a,c){this.log("resourceAccessList: "+a.join(","),!0);void 0==a||"object"!=typeof a?this.log("resourceAccessList: no resourceid_array provided"+("object"!=typeof a),!0):1!=c&&0!=this._use_cache("authz_query_list",
a)||this._call_ais("resourceAccessList",a)};b.prototype.channelAccess=function(a,c){this.log("channelAccess: "+a,!0);1!=c&&0!=this._use_cache("authz_query",a)||this._call_ais("channelAccess",a)};b.prototype.resources=function(a){this.log("resources ",!0);1!=a&&0!=this._use_cache("resources")||this._call_ais("resources")};b.prototype.registerDevice=function(a){this.log("registerDevice ",!0);this._call_ais("registerDevice",a)};b.prototype.vcsGet=function(a,c){this.log("vcsGet: "+a,!0);void 0==a||""==
a?this.log("vcsGet: no contentid provided",!0):1!=c&&0!=this._use_cache("vcs",a)||this._call_ais("vcsGet",a)};b.prototype.vcsSet=function(a,c){this.log("vcsSet: "+a+","+c,!0);this._call_ais("vcsSet",a,c)};b.prototype.vcsList=function(a,c){this.log("vcsList: "+(void 0!=a?a.join(","):"no contentid_array"),!0);1!=c&&0!=this._use_cache("vcs_list",a)||this._call_ais("vcsList",a)};b.prototype.vcsListRecent=function(a,c){this.log("vcsListRecent: "+a,!0);1!=c&&0!=this._use_cache("vcs_list",a)||this._call_ais("vcsListRecent",
a)};b.prototype.loginFormat=function(a,c){return this.protocol+this.baseurl+this.platform_id+"/init/"+a+"?responsemethod=redirect&format=jsonp"+(void 0!=c&&""!=c?"&responsetarget="+c:"")+(""!=this.language_override?"&lang="+this.language_override:"")};b.prototype.logoutFormat=function(a){return this.protocol+this.baseurl+this.platform_id+"/slo/?responsemethod=redirect&format=jsonp"+(void 0!=a?"&responsetarget="+a:"")};b.prototype.login=function(a){this.log("ais_client.login DEPRECATED. Use ais_client.loginFormat instead.",
!0);return this.protocol+this.baseurl+this.platform_id+"/init/"+a+"?format=jsonp"};b.prototype.setLogging=function(a,c){1==a?(this.use_logging=a,this.log("setLogging: Logging enabled ("+(void 0!=c&&document.getElementById(c)?"HTML - "+c:"console.log")+")",!0)):(this.log("setLogging: Logging disabled",!0),this.use_logging=a);void 0!=c?document.getElementById(c)&&(this.log_target=c):this.log_target=""};b.prototype.setCacheTime=function(a,c){var b=!1;if("number"==typeof c)switch(a){case "init":case "chooser":case "authz_query":case "identity":case "bounce":case "echo_response":case "vcs":case "resources":case "vcs_list":case "authz_query_list":this.cache_time[a]=
c,b=!0}this.log("setCache ("+a+","+c+") "+(1==b?"changed successfully":"invalid call"),!0);this.log(this.cache_time);return b};b.prototype.setUseCache=function(a){1!=a&&0!=a||a==this.use_cache||(this.use_cache=a,this.log("setUseCache: changed to (use_cache="+a+")",!0));this.log("setUseCache: (use_cache="+this.use_cache+")",!0)};b.prototype.setScriptInsert=function(a){this.script_insert_type="";"jquery"==a&&(this.script_insert_type=a);this.log("setScriptInsert ("+a+")",!0)};b.prototype.setRedirectLocation=
function(a){this.log("setRedirectLocation ("+a+")",!0);this._set("ais_client_redirect_location",a)};b.prototype.getRedirectLocation=function(){this.log("getRedirectLocation ("+this._get("ais_client_redirect_location")+")",!0);return this._get("ais_client_redirect_location")};b.prototype.clearRedirectLocation=function(){this._clear("ais_client_redirect_location");this.log("clearRedirectLocation",!0)};b.prototype.log=function(a,c){var b=1==c?"[AIS] "+a:a;if(this.log_object_keys.length>=this.log_object_size){var d=
this.log_object_keys.shift();delete this.log_object[d]}d=new Date;d=d.getFullYear()+"-"+d.getMonth()+"-"+d.getDate()+" "+d.getHours()+":"+d.getMinutes()+":"+d.getSeconds()+"."+d.getMilliseconds();this.log_object[d]=b;this.log_object_keys[this.log_object_keys.length]=d;1==this.use_logging&&(window.console&&console.log&&console.log(b),""!=this.log_target&&(d="","object"==typeof a&&(d=d+"<br>"+this._create_object_log_output(a),b="[AIS] "+b+d),document.getElementById(this.log_target).innerHTML+="<div"+
(0==this.log_toggle?"":' style="background: #E8E8E8;"')+">"+b+"</div>",this.log_toggle=1==this.log_toggle?0:1))};b.prototype._call_ais=function(a,c,b){var d=this.protocol+this.baseurl+this.platform_id;"echo"==a?d+="/echo/"+c:"bounce"==a?d+="/bounce/":"init"==a?d+="/init/":"chooser"==a?d+="/chooser/":"identity"==a?d+="/identity/":"resourceAccess"==a?d+="/identity/resourceAccess/"+c:"channelAccess"==a?d+="/identity/channelAccess/"+c:"resources"==a?d+="/identity/resourceAccess/":"registerDevice"==a?
d+="/identity/registerDevice/"+c:"vcsGet"==a?d+="/vcs/"+c:"vcsList"==a?d+="/vcs/":"vcsListRecent"==a?d+="/vcs/":"vcsSet"==a?d+="/vcs/"+c:"resourceAccessList"==a&&(d+="/identity/resourceAccess/");d+="?format=jsonp&responsefield="+this.responsefield;"vcsSet"==a&&(d+="&ph_pos="+b+"&trickmode=post");"vcsList"==a&&void 0!=c&&null!=c&&""!=c&&(d+="&content_id="+c.join("&content_id="));"vcsListRecent"==a&&void 0!=c&&null!=c&&""!=c&&(d+="&limit="+c);"resourceAccessList"==a&&(d+="&resource_id="+c.join("&resource_id="));
""==this.language_override||"resourceAccess"!=a&&"channelAccess"!=a&&"resourceAccessList"!=a||(d+="&lang="+this.language_override);this.log(a+": "+d,!0);"jquery"==this.script_insert_type?jQuery.ajax({url:d,dataType:"script",cache:!0,async:!0}):(a=document.createElement("script"),a.setAttribute("src",d),document.getElementsByTagName("head")[0].appendChild(a))};b.prototype._mkboolean=function(a){return/^true$/i.test(a)};b.prototype._isFunction=function(a){return!!a&&a.constructor==Function};b.prototype._nullhandler=
function(a,c){};b.prototype._alerthandler=function(a,c){alert("alert handler received message of type: "+a+"\n with: "+c,!0)};b.prototype._dispatch=function(a,c){void 0!==this.callbacks[a]&&this._isFunction(this.callbacks[a])?(runner=this.callbacks[a],runner(a,c)):this.log("callable is not set for handler: "+a,!0)};b.prototype._create_object_log_output=function(a){var c="{";for(key in a)"object"==typeof a[key]?(c+=""+("string"==typeof key?'"'+key+'"':key)+":",c+=this._create_object_log_output(a[key]),
c+=", "):c+=""+("string"==typeof key?'"'+key+'"':key)+":"+("string"==typeof a[key]?'"'+a[key]+'"':a[key])+", ";c=c.substring(0,c.length-2);return c+"}"};b.prototype._use_cache=function(a,c){var b=!1;if(0==this.use_cache)return this.log("_use_cache: caching disabled",!0),b;var d=0,e="",h=new Date,f=a;"authz_query"==f||"vcs"==f?f+="-"+c:"echo_response"==f?f+="-"+escape(c):"vcs_list"==f&&(f+="-"+("object"!=typeof c?c:c.join("-")));b=void 0;1==this.supportsLocalStorage&&(b=localStorage.getItem(this.ls_prepend+
this.platform_id+"__response_cache_update__"+f));void 0!==this.response_cache._response_cache_updates[f]?(d=this.response_cache._response_cache_updates[f],e="js"):void 0!=b&&(d=b,e="localStorage");0<d&&h.getTime()-d<this.cache_time[a]?("js"==e?window[this.responsefield+"(this.response_cache[response_call],true)"]:"localStorage"==e&&window[this.responsefield+'(JSON.parse(localStorage.getItem(this.ls_prepend+this.platform_id+"__"+response_call)),true)'],b=!0,this.log("_use_cache: "+f+" ("+e+" cached "+
(this.cache_time[a]-(h.getTime()-d))+"/"+this.cache_time[a]+")",!0)):(b=!1,1==this.supportsLocalStorage&&(localStorage.removeItem(this.ls_prepend+this.platform_id+"__response_cache_update__"+f),localStorage.removeItem(this.ls_prepend+this.platform_id+"__"+f)));return b};b.prototype._set_cache=function(a){var c=new Date,b=a._type;if("authz_query"==b)b=a._type+"-"+a.resource;else if("echo_response"==b)b+="-"+escape(a.response_value);else if("vcs"==b)b+="-"+escape(a.content_id);else if("vcs_list"==b)for(i=
0;i<a.documents.length;i++)b+="-"+a.documents[i].content_id;if(void 0===this.response_cache[b]||c.getTime()-this.response_cache._response_cache_updates[b]>this.cache_time[a._type]){var d=void 0;1==this.supportsLocalStorage&&(d=localStorage.getItem(this.ls_prepend+this.platform_id+"__response_cache_update__"+b));this.response_cache._response_cache_updates[b]=void 0!=d?d:c.getTime();1==this.supportsLocalStorage&&localStorage.setItem(this.ls_prepend+this.platform_id+"__response_cache_update__"+b,c.getTime())}this.response_cache[b]=
a;1==this.supportsLocalStorage&&localStorage.setItem(this.ls_prepend+this.platform_id+"__"+b,JSON.stringify(a));this.log("_set_cache: "+b+" (caching length = "+this.cache_time[a._type]+")",!0);this.log(this.response_cache)};b.prototype._reset_cache=function(a){this.response_cache={_response_cache_updates:{}};if(1==a&&1==this.supportsLocalStorage){a=[];for(i=0;i<=localStorage.length-1;i++)a[i]=localStorage.key(i);var b=this.ls_prepend+this.platform_id+"__";for(i=0;i<=a.length-1;i++)a[i].substring(0,
b.length)==b&&(this.log("_reset_cache: Removing| "+a[i],!0),localStorage.removeItem(a[i]))}};b.prototype._set=function(a,b,g){if(1==this.supportsLocalStorage)return this.log('_set: using localStorage (key: "'+a+'", value: "'+b+'")',!0),localStorage.removeItem(a),localStorage.setItem(a,escape(b));var c="";g&&(c=new Date,c.setTime(c.getTime()+864E5*g),c="; expires="+c.toGMTString());document.cookie=a+"="+escape(b)+c+"; path=/";this.log('_set: using cookies (key: "'+a+'", value: "'+b+'", expires: "'+
c+'", cookie_value: "'+a+"="+b+c+'; path=/")',!0)};b.prototype._get=function(a){if(1==this.supportsLocalStorage)return this.log('_get: using localStorage (key: "'+a+'", value: "'+localStorage.getItem(a)+'")',!0),unescape(localStorage.getItem(a));for(var b=a+"=",g=document.cookie.split(";"),d=0;d<g.length;d++){for(var e=g[d];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(b))return this.log('_get: using cookies (key: "'+a+'", value: "'+e.substring(b.length,e.length)+'")',!0),unescape(e.substring(b.length,
e.length))}return null};b.prototype._clear=function(a){1==this.supportsLocalStorage?localStorage.removeItem(a):this._set(a,"",-1)};b.prototype._setLocalStorageSupport=function(){this.supportsLocalStorage=this.__checkLocalStorageSupport()};b.prototype.__checkLocalStorageSupport=function(){try{return JSON.stringify({a:"b"}),"localStorage"in window&&null!==window.localStorage}catch(a){return!1}};window.ais_client=new b;window.ais_client._reset_cache();window.ais_client._setLocalStorageSupport()})();
